-- CreateTable
CREATE TABLE "ExecutiveReport" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL,
    "cpu_manufacturer" TEXT NOT NULL,
    "cpu_brand" TEXT NOT NULL,
    "cpu_cores" INTEGER NOT NULL,
    "cpu_speed" DOUBLE PRECISION NOT NULL,
    "cpu_usage" INTEGER NOT NULL,
    "cpu_load_user" INTEGER NOT NULL,
    "cpu_load_system" INTEGER NOT NULL,
    "cpu_load_idle" INTEGER NOT NULL,
    "cpu_temperature" DOUBLE PRECISION,
    "memory_total" DOUBLE PRECISION NOT NULL,
    "memory_used" DOUBLE PRECISION NOT NULL,
    "memory_free" DOUBLE PRECISION NOT NULL,
    "memory_swap_used" DOUBLE PRECISION NOT NULL,
    "memory_cache" DOUBLE PRECISION NOT NULL,
    "disk_total" DOUBLE PRECISION NOT NULL,
    "disk_used" DOUBLE PRECISION NOT NULL,
    "disk_free" DOUBLE PRECISION NOT NULL,
    "disk_usage_percent" INTEGER NOT NULL,
    "network_rx_sec" DOUBLE PRECISION NOT NULL,
    "network_tx_sec" DOUBLE PRECISION NOT NULL,
    "network_errors" INTEGER NOT NULL,
    "network_dropped" INTEGER NOT NULL,
    "system_uptime" DOUBLE PRECISION NOT NULL,
    "system_os" TEXT NOT NULL,
    "system_kernel" TEXT NOT NULL,
    "system_hostname" TEXT NOT NULL,
    "top_processes" JSONB NOT NULL,

    CONSTRAINT "ExecutiveReport_pkey" PRIMARY KEY ("id")
);
